version: '3.7'

services:

  ui:
    image: harness/ui-signed:71000
    expose:
      - '8080'
    networks:
      harness-network:

  ng-ui:
    image: harness/nextgenui:0.266.1
    environment:
      - API_URL=${PUBLIC_URL:?err}
    expose:
      - '8080'
    networks:
      harness-network:

  manager:
    image: bazel/360-cg-manager/container:manager
    depends_on:
      - mongo
      - redis
    env_file:
      - environment/manager.env
    environment:
      - API_URL=${PUBLIC_URL:?err}
    expose:
      - '7145'
      - '9090'
      - '9879'
      - '54327'
    networks:
      harness-network:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3072M
        reservations:
          memory: 2200M

  ng-manager:
    image: bazel/120-ng-manager/container:ng_manager
    depends_on:
      - mongo
      - pipeline-service
      - redis
    env_file: environment/ng-manager.env
    expose:
      - '7090'
    networks:
      harness-network:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          memory: 3200M

  pipeline-service:
    image: bazel/800-pipeline-service/container:pipeline_service
    depends_on:
      - mongo
      - redis
    env_file: environment/pipeline-service.env
    expose:
      - '12001'
      - '12011'
    networks:
      harness-network:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3072M
        reservations:
          memory: 2200M

  platform-service:
    image: bazel/820-platform-service/container:platform_service
    depends_on:
      - mongo
      - redis
    env_file: environment/platform-service.env
    expose:
      - '9005'
    networks:
      harness-network:

  gateway:
    image: harness/gateway:100070
    depends_on:
      - mongo
      - redis
    env_file: environment/gateway.env
    expose:
      - '8080'
    networks:
      harness-network:

  log-service:
    image: harness/log-service:releaseBuild-11
    depends_on:
      - mongo
      - redis
    env_file: environment/log-service.env
    expose:
      - '12011'
    networks:
      harness-network:

  delegate-proxy:
    image: bazel/dockerization/delegate-proxy:delegate_proxy
    expose:
      - '8080'
    networks:
      harness-network:

  proxy:
    image: nginx:latest
    expose:
      - '80'
    depends_on:
      - delegate-proxy
      - manager
      - ui
      - ng-manager
      - ng-ui
    networks:
      harness-network:
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:6.2.5-alpine
    expose:
      - '6379'
    networks:
      harness-network:

  mongo:
    image: mongo:4.2.8
    command: -f /etc/mongod.conf
    networks:
      harness-network:
    volumes:
      - mongo_data:/data/db
      - ./config/mongo/mongod.conf:/etc/mongod.conf

networks:
  harness-network:
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  mongo_data:
