
## Harness application will be installed in this namespace in the given cluster
kubernetesClusterNamespace: harness

accounts:
  accountName: Demo-Account
  companyName: Demo-Company
  adminEmail: admin@harness.io

# Private docker registry/repository details
docker:
  registry:
    url:
    username:
    password:
    authsUrl:
    email:

inframapping:
  lbUrl: http://127.0.0.1
  lbIpAddress: 127.0.0.1
  lbHost: example.com
