accounts:
  accountName:
  adminEmail:
  companyName:
  accountId:
  accountSecret:
images:
  manager:
    repository:
    tag:
  le:
    repository:
    tag:
  ui:
    repository:
    tag:
  mongo:
    repository:
    tag:
  defaultBackend:
    repository:
    tag:
  ingressController:
    repository:
    tag:
  nginx:
    repository:
    tag:
  delegate:
    repository:
    tag:
inframapping:
  lbIpAddress:
  lbUrl:
kubernetesClusterNamespace:
docker:
  registry:
    url:
    username:
    password:
    authsUrl:
    email:
appSecrets:
  learningEngineSecret:
secrets:
  jwtAuthSecret:
  jwtExternalServiceSecret:
  jwtMultiAuthSecret:
  jwtPasswordSecret:
  jwtSsoRedirectSecret:
  jwtZendeskSecret:
  licenseInfo:
services:
  mongo:
    adminUser: admin
    adminPassword: adminpass
    key: harness
    configMap:
      init:
    size: 200Gi
    storageClass: harness-mongo-persistent-volume
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
  manager:
    storageClass: harness-manager-persistent-volume
    size: 75Gi
    resources:
      limits:
        cpu: "2"
        memory: "5Gi"
  ui:
    resources:
      limits:
        cpu: "0.2"
        memory: "0.2Gi"
  learningEngine:
    resources:
      limits:
        cpu: "8"
        memory: "2Gi"
  verificationService:
    resources:
      limits:
        cpu: "1"
        memory: "3Gi"