apiVersion: v1
stringData:
  .dockercfg: '{"{{ .Values.privatedockerrepo.docker_reg_auths_url }}":{"username":"{{ .Values.privatedockerrepo.docker_registry_username }}","password":"{{ .Values.privatedockerrepo.docker_registry_password }}","email":"{{ .Values.privatedockerrepo.docker_registry_email }}"}}'
kind: Secret
metadata:
  name: regcred
  namespace: harness
type: kubernetes.io/dockercfg
