accountId: kmpySmUISimoRrJL6NL73w
accountSecret: 2f6b0988b6fb3370073c3d0505baee59
managerUrl: https://localhost:9090/api/
doUpgrade: false
upgradeCheckLocation: https://ci.harness.io/storage/wingswatchers/watcherci.txt
upgradeCheckIntervalSeconds: 60
