xxxxxxxx
  registerDefaultExceptionMappers: false
  rootPath: /api
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9090
  adminContextPath: /admin
  adminMinThreads: 1
  adminMaxThreads: 64
  adminConnectors:
    - type: http
      port: 9091
logging:
  appenders:
    - type: console
      threshold: INFO
      target: stdout

mongo:
  host: localhost
  port: 27017
  db: wings

portal:
  url: http://ec2-50-16-106-255.compute-1.amazonaws.com:3456

jenkinsBuildQuerySize: 50

enableAuth: true

assets:
  mimeTypes:
    js: application/json; charset=UTF-8

swagger:
  resourcePackage: software.wings.resources,software.wings.utils
