mongo:
  uri: mongodb://localhost:27017/pms-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

cdGrpcClientConfig:
  target: localhost:12201
  authority: localhost

cvGrpcClientConfig:
  target: localhost:12202
  authority: localhost

allowedOrigins:
  - "*"
