harness-mongo:
  uri: mongodb://localhost:27017/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 50
events-mongo:
  uri: mongodb://localhost:27017/events
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300


timescaledb:
  timescaledbUrl: "jdbc:postgresql://localhost:5432/harness"
  timescaledbUsername: "postgres"
  timescaledbPassword:
  connectTimeout: 10
  socketTimeout: 30
  logUnclosedConnections: false
  loggerLevel: OFF

awsS3SyncConfig:
  awsS3BucketName: awsS3BucketNamePlaceHolder
  awsAccessKey: awsS3SyncAccessKeyPlaceHolder
  awsSecretKey: awsS3SyncSecretKeyPlaceHolder
  region: awsS3SyncRegionPlaceHolder

awsDataPipelineConfig:
  gcpServiceAccount: gcpServiceAccountPlaceHolder
  gcpProjectId : gcpProjectIdPlaceHolder
  gcsBasePath: gcsBasePathPlaceHolder

