xxxxxxxx
  applicationConnectors:
    - type: https
      port: 7090
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
      maxRequestHeaderSize: 100KiB
    - type: http
      port: 7457
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: https
      port: 7091
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
  requestLog:
    appenders: []
  maxThreads: 1024

nextGen:
  managerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  cvNgServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  userVerificationSecret: dyBvaWVmbGRrYyB6aHpjeHZvaWxzamt6ZGN6c2RhZmh5dBrebhmnjryRe54rX43W3565ytgbsDvnjws5
  ngManagerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  jwtAuthSecret: dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq
  identityServiceSecret: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=

scmConnectionConfig:
  url: localhost:8091

allowedOrigins:
  - https://localhost:8181
  - https://127.0.0.1:8181
  - http://localhost:8000
  - http://127.0.0.1:8000
  - https://localhost:8000
  - https://127.0.0.1:8000

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"

mongo:
  uri: mongodb://localhost:27017/ng-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

#[secondary-db] : Uncomment the following if you want to connect to another database
#secondary - mongo:
#uri : mongodb:  // localhost:27017/cd-nextgen-secondary
#connectTimeout : 30000
#serverSelectionTimeout : 90000
#maxConnectionIdleTime : 600000
#connectionsPerHost : 300
#indexManagerMode : AUTO

pmsMongo:
  uri: mongodb://localhost:27017/pms-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

managerClientConfig:
  baseUrl: http://localhost:3457/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

ngManagerClientConfig:
  baseUrl: http://localhost:7457/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

enableAuth: true

grpcClient:
  target: localhost:9880
  authority: localhost

grpcServer:
  connectors:
    - port: 9980
      secure: true
      keyFilePath: key.pem
      certFilePath: cert.pem
    - port: 9979

smtp:
  type: SMTP
  host: host_placeholder
  port: 465
  fromAddress: noreply@harness.io
  useSSL: true
  username: smtp_username_placeholder
  password: "smtp_password_placeholder"

eventsFramework:
  redis:
    sentinel: false
    masterName: "mymaster"
    redisUrl: "dummyRedisUrl"
    sentinelUrls:
      - redis://localhost:26379
    envNamespace: ""
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true

pmsSdkGrpcServerConfig:
  connectors:
    - port: 12101

pmsGrpcClientConfig:
  target: localhost:12011
  authority: localhost

shouldConfigureWithPMS: false
