apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-config
data:
  key: value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: nginx
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: {{.Values.name}}
        image: nginx:1.15.4
        envFrom:
        - configMapRef:
            name: {{.Values.name}}-config
        ports:
        - containerPort: 80