apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-config
data:
  key: value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        envFrom:
        - configMapRef:
            name: {{.Values.name}}-config
        ports:
        - containerPort: 80