accountId: kmpySmUISimoRrJL6NL73w
accountSecret: 2f6b0988b6fb3370073c3d0505baee59
managerUrl: https://localhost:9090/api/
verificationServiceUrl: https://localhost:7070/verification/
cvNextGenUrl: https://localhost:6060/cv-nextgen/
heartbeatIntervalMs: 60000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
managerTarget: localhost:9880
managerAuthority: localhost
queueFilePath: ../eventQueue
grpcServiceEnabled: true
grpcServiceConnectorPort: 8080
managerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

