xxxxxxxx
  applicationConnectors:
    - type: h2
      port: 9080
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
      maxRequestHeaderSize: 100KiB
    - type: http
      port: 3458
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: h2
      port: 9092
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
  requestLog:
    appenders:
      - type: console
        target: STDOUT
        threshold: ERROR
  maxThreads: 1024

distributedLockImplementation: MONGO

atmosphereBroadcaster: HAZELCAST

redisAtmosphereConfig:
  sentinel: false
  masterName: "test"
  redisUrl: "redis://localhost:6379"
  sentinelUrls:
    - "redis://redis1:26379"
    - "redis://redis2:26379"
    - "redis://redis3:26379"
  envNamespace: ""
  readMode: MASTER
  nettyThreads: 16
  useScriptCache: true

cacheConfig:
  cacheBackend: HAZELCAST
  cacheNamespace: ""
  disabledCaches: []

logging:
  level: INFO
  loggers:
    com.novemberain.quartz.mongodb: WARN
    org.quartz.plugins: WARN
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    # the following is to suppress "Error retrieving job for trigger XYZ, setting trigger state to ERROR."
    # TODO: remove this suppression when the mentioned issue is resolved
    com.novemberain.quartz.mongodb.TriggerRunner: "OFF"
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false
    - type: file
      threshold: TRACE
      currentLogFilename: portal.log
      archive: true
      archivedFileCount: 15
      maxFileSize: 150MB
      archivedLogFilenamePattern: portal.%d.%i.log
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"

deployMode: KUBERNETES



jreConfigs:
  oracle8u191:
    version: 1.8.0_191
    jreDirectory: jre1.8.0_191
    jreMacDirectory: jre1.8.0_191.jre
    jreTarPath: jre/8u191/jre-8u191-${OS}-x64.tar.gz
  openjdk8u242:
    version: 1.8.0_242
    jreDirectory: jdk8u242-b08-jre
    jreMacDirectory: jdk8u242-b08-jre
    jreTarPath: jre/openjdk-8u242/jre_x64_${OS}_8u242b08.tar.gz

redisLockConfig:
  sentinel: false
  masterName: "test"
  redisUrl: "redis://localhost:6379"
  sentinelUrls:
    - "redis://redis1:26379"
    - "redis://redis2:26379"
    - "redis://redis3:26379"
  envNamespace: ""
  readMode: MASTER
  nettyThreads: 16
  useScriptCache: true

eventsFramework:
  redis:
    sentinel: false
    masterName: "test"
    redisUrl: "redis://localhost:6379"
    sentinelUrls:
      - "redis://redis1:26379"
      - "redis://redis2:26379"
      - "redis://redis3:26379"
    envNamespace: ""
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true
    userName: ""
    password: ""

mongo:
  uri: mongodb://localhost:27017/harness
  #uri: mongodb://mongo1:30001,mongo2:30002,mongo3:30003/harness
  #locksUri: mongodb://localhost:27017/impermanent
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO


#Delegate Service specific configs & gRpc configs
#delegateServiceUrl: https://localhost:9080/
grpcServerConfig:
  connectors:
    - port: 14011
      secure: true
      keyFilePath: key.pem
      certFilePath: cert.pem
    - port: 9878

grpcServerClassicConfig:
  connectors:
    - port: 15011
      secure: true
      keyFilePath: key.pem
      certFilePath: cert.pem
    - port: 9879

#grpcDelegateServiceClientConfig:
 # target: localhost:14011
  #authority: localhost

delegateServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM


