roles:
    - identifier: _project_admin
      name: Project Admin
      description: Administrate an existing project.
      permissions:
        - core.project.view
        - core.project.edit
        - core.project.delete
        - core.secret.create
        - core.secret.view
        - core.secret.edit
        - core.secret.delete
        - core.connector.create
        - core.connector.view
        - core.connector.edit
        - core.connector.delete
        - core.pipeline.view
        - core.pipeline.edit
        - core.pipeline.delete
        - core.pipeline.execute
      allowedScopeLevels:
        - project
      managed: true
    - identifier: _project_viewer
      name: Project Viewer
      description: View a project
      permissions:
        - core.project.view
        - core.secret.view
        - core.connector.view
        - core.pipeline.view
      allowedScopeLevels:
        - project
      managed: true
    - identifier: _organization_admin
      name: Organization Admin
      description: Administer an existing organizationn
      permissions:
        - core.organization.view
        - core.organization.edit
        - core.organization.delete
        - core.project.create
        - core.secret.create
        - core.secret.view
        - core.secret.edit
        - core.secret.delete
        - core.connector.create
        - core.connector.view
        - core.connector.edit
        - core.connector.delete
      allowedScopeLevels:
        - organization
      managed: true
    - identifier: _organization_viewer
      name: Organization Viewer
      description: View an organization
      permissions:
        - core.organization.view
        - core.secret.view
        - core.connector.view
      allowedScopeLevels:
        - organization
      managed: true
    - identifier: _account_admin
      name: Account Admin
      description: Administer an account
      permissions:
        - core.account.edit
        - core.account.delete
        - core.organization.create
        - core.secret.create
        - core.secret.view
        - core.secret.edit
        - core.secret.delete
        - core.connector.create
        - core.connector.view
        - core.connector.edit
        - core.connector.delete
      allowedScopeLevels:
        - account
      managed: true
    - identifier: _account_viewer
      name: Account Viewer
      description: View an account
      permissions:
        - core.secret.view
        - core.connector.view
      allowedScopeLevels:
        - account
      managed: true
    - identifier: _pipeline_executor
      name: Pipeline Executor
      description: Execute a pipeline
      permissions:
        - core.secret.view
        - core.connector.view
        - core.pipeline.view
        - core.pipeline.execute
      allowedScopeLevels:
        - project
      managed: true