- roles:
    - identifier: project-admin
      name: Project Admin
      description: Administrate an existing project.
      permissions:
        - core.project.view
        - core.project.edit
        - core.project.delete
      allowedScopeLevels:
        - project
    - identifier: project-viewer
      name: Project Viewer
      description: View a project
      permissions:
        - core.project.view
      allowedScopeLevels:
        - project
    - identifier: organization-admin
      name: Organization Admin
      description: Administer an existing organizationn
      permissions:
        - core.organization.view
        - core.organization.edit
        - core.organization.delete
        - core.project.create
        - core.project.view
        - core.project.edit
        - core.project.delete
      allowedScopeLevels:
        - organization
    - identifier: organization-viewer
      name: Organization Viewer
      description: View an organization
      permissions:
        - core.organization.view
        - core.project.view
      allowedScopeLevels:
        - organization
    - identifier: account-admin
      name: Account Admin
      description: Administer an account
      permissions:
        - core.account.edit
        - core.account.delete
        - core.organization.create
        - core.organization.view
        - core.organization.edit
        - core.organization.delete
      allowedScopeLevels:
        - account
    - identifier: account-viewer
      name: Account Viewer
      permissions:
        - core.organization.view
        - core.project.view