[package]
name = "aeriform"
version = "0.1.0"
authors = ["George Georgiev <george@harness.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
regex = "1.4.3"
multimap = "0.8.2"
lazy_static = "1.4.0"
clap = "3.0.0-beta.2"



