# For details: https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.services.mongo.storageClass }}
  namespace: {{ .Values.kubernetesClusterNamespace }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.services.manager.storageClass }}
  namespace: {{ .Values.kubernetesClusterNamespace }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain