# For details: https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.services.mongo.storageClass }}
  namespace: {{ .Values.kubernetesClusterNamespace }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: dedicated
reclaimPolicy: Retain

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.services.manager.storageClass }}
  namespace: {{ .Values.kubernetesClusterNamespace }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: dedicated
reclaimPolicy: Retain