CARD_VIEW_SORT_BY:
    - name: Most Recent
      value: mostRecent
    - name: Alphabetical Ascending
      value: alphabeticalAscending
    - name: Alphabetical Descending
      value: alphabeticalDescending
      
ARTIFACT_TYPE:
    - name: WAR
      value: WAR
    - name: TAR
      value: TAR
      
DEPLOYMENT_STRATEGY:
    - name: SERIAL
      value: SERIAL
    - name: PARALLEL
      value: PARALLEL

    
      