CardviewSortBy:
    - name: Most Recent
      value: mostRecent
    - name: Alphabetical Ascending
      value: alphabeticalAscending
    - name: Alphabetical Descending
      value: alphabeticalDescending
      
ArtifactType:
    - name: WAR
      value: WAR
    - name: TAR
      value: TAR

    
      