CARD_VIEW_SORT_BY:
    - name: Most Recent
      value: mostRecent
    - name: Alphabetical Ascending
      value: alphabeticalAscending
    - name: Alphabetical Descending
      value: alphabeticalDescending
      
ARTIFACT_TYPE:
    - name: JAR File
      value: JAR
    - name: TAR File
      value: TAR
    - name: WAR File
      value: WAR
    - name: ZIP File
      value: ZIP
    - name: Docker Image
      value: DOCKER
    - name: Other
      value: OTHER

ARTIFACT_SOURCE_TYPE:
    - name: Jenkins Server
      value: JENKINS
    - name: Bamboo Server
      value: BAMBOO
    - name: Docker Repository
      value: DOCKER
    - name: Nexus Repository
      value: NEXUS

DEPLOYMENT_STRATEGY:
    - name: Serial
      value: SERIAL
    - name: Parallel
      value: PARALLEL

OS_TYPE:
    - name: Linux - RHL
      value: RHL
    - name: Linux - DEB
      value: DEB

CONNECTION_TYPE:
    - name: SSH
      value: SSH
    - name: VPN
      value: VPN

ACCESS_TYPE:
    - name: SSH
      value: SSH
    - name: SSH_KEY
      value: SSH_KEY
    - name: SSH_USER_PASSWD
      value: SSH_USER_PASSWD
    - name: SSH_SU_APP_ACCOUNT
      value: SSH_SU_APP_ACCOUNT
    - name: SSH_SUDO_APP_ACCOUNT
      value: SSH_SUDO_APP_ACCOUNT

EXECUTION_TYPE:
    - name: SSH
      value: SSH

CONTAINER_FAMILY:
    - name: Tomcat
      value: TOMCAT
    - name: JBoss AS 7
      value: JBOSS

WORKFLOW_ORCHESTRATION_TYPE:
    - name: Canary Deployment Workflow
      value: CANARY
    - name: Blue/Green Deployment Workflow
      value: BLUE_GREEN

FAILURE_TYPE:
    - name: Connectivity Error
      value: CONNECTIVITY
    - name: Authentication Failure
      value: AUTHENTICATION
    - name: Application Error
      value: APPLICATION_ERROR

EXECUTION_SCOPE:
    - name: Workflow
      value: WORKFLOW
    - name: Workflow Phase
      value: WORKFLOW_PHASE

NOTIFICATION_CONDITION:
    - name: Success
      value: SUCCESS
    - name: Failure
      value: FAILED
    - name: Paused
      value: PAUSED

REPAIR_ACTION_CODE:
    - name: Maanual Intervention
      value: MANUAL_INTERVENTION
    - name: Rollback Workflow Execution
      value: ROLLBACK_WORKFLOW
    - name: Rollback Phase Execution
      value: ROLLBACK_PHASE
    - name: Ignore
      value: IGNORE

PHASE_STEP_TYPE:
    - name: Provision Nodes
      value: PROVISION_NODE
    - name: Disable/Unpublish Services
      value: DISABLE_SERVICE
    - name: Deploy Services
      value: INSTALL
    - name: Enable/Publish Services
      value: ENABLE_SERVICE
    - name: Verify Services
      value: VERIFY_SERVICE
    - name: Deprovision Nodes
      value: DEPROVISION_NODE
    - name: Wrap up
      value: WRAP_UP

DEPLOYMENT_TYPE:
    - name: SSH
      value: SSH
    - name: Amazon EC2 Container
      value: ECS
    - name: Kubernetes
      value: KUBERNETES

ENVIRONMENT_TYPE:
    - name: Production
      value: PROD
    - name: Non Production
      value: NON_PROD

ROLE_TYPE:
    - name: Account Administrator
      value: ACCOUNT_ADMIN
    - name: Application Administrator
      value: APPLICATION_ADMIN
    - name: Production Support
      value: PROD_SUPPORT
    - name: Non-production Support
      value: NON_PROD_SUPPORT

OVERRIDE_TYPE:
    - name: Entire Environment
      value: ALL
    - name: Override Specific Instances
      value: INSTANCES
    - name: Override Specific Zones/Tags etc.
      value: CUSTOM

SERVICE_VARIABLE_TYPE:
    - name: Text
      value: TEXT
    - name: Load Balancer
      value: LB
