CARD_VIEW_SORT_BY:
    - name: Most Recent
      value: mostRecent
    - name: Alphabetical Ascending
      value: alphabeticalAscending
    - name: Alphabetical Descending
      value: alphabeticalDescending
      
ARTIFACT_TYPE:
    - name: JAR
      value: JAR
    - name: TAR
      value: TAR
    - name: WAR
      value: WAR
    - name: ZIP
      value: ZIP
    - name: DOCKER
      value: DOCKER
    - name: OTHER
      value: OTHER

ARTIFACT_SOURCE_TYPE:
    - name: JENKINS
      value: JENKINS
    - name: BAMBOO
      value: BAMBOO
    - name: DOCKER
      value: DOCKER

DEPLOYMENT_STRATEGY:
    - name: SERIAL
      value: SERIAL
    - name: PARALLEL
      value: PARALLEL

OS_TYPE:
    - name: Linux - RHL
      value: RHL
    - name: Linux - DEB
      value: DEB

CONNECTION_TYPE:
    - name: SSH
      value: SSH
    - name: VPN
      value: VPN

ACCESS_TYPE:
    - name: SSH
      value: SSH
    - name: SSH_KEY
      value: SSH_KEY
    - name: SSH_USER_PASSWD
      value: SSH_USER_PASSWD
    - name: SSH_SU_APP_ACCOUNT
      value: SSH_SU_APP_ACCOUNT
    - name: SSH_SUDO_APP_ACCOUNT
      value: SSH_SUDO_APP_ACCOUNT

EXECUTION_TYPE:
    - name: SSH
      value: SSH

CONTAINER_FAMILY:
    - name: Tomcat
      value: TOMCAT
    - name: JBoss AS 7
      value: JBOSS

WORKFLOW_ORCHESTRATION_TYPE:
    - name: Canary Deployment Workflow
      value: CANARY
    - name: Blue/Green Deployment Workflow
      value: BLUE_GREEN

FAILURE_TYPE:
    - name: Connectivity Error
      value: CONNECTIVITY
    - name: Authentication Failure
      value: AUTHENTICATION
    - name: Application Error
      value: APPLICATION_ERROR

EXECUTION_SCOPE:
    - name: Workflow
      value: WORKFLOW
    - name: Workflow Phase
      value: WORKFLOW_PHASE

NOTIFICATION_CONDITION:
    - name: Success
      value: SUCCESS
    - name: Failure
      value: FAILED
    - name: Paused
      value: PAUSED

REPAIR_ACTION_CODE:
    - name: Maanual Intervention
      value: MANUAL_INTERVENTION
    - name: Rollback Workflow Execution
      value: ROLLBACK_WORKFLOW
    - name: Rollback Phase Execution
      value: ROLLBACK_PHASE
    - name: Ignore
      value: IGNORE

PHASE_STEP_TYPE:
    - name: Provision Nodes
      value: PROVISION_NODE
    - name: Disable/Unpublish Services
      value: DISABLE_SERVICE
    - name: Deploy Services
      value: DEPLOY_SERVICE
    - name: Enable/Publish Services
      value: ENABLE_SERVICE
    - name: Verify Services
      value: VERIFY_SERVICE
    - name: Deprovision Nodes
      value: DEPROVISION_NODE
    - name: Wrap up
      value: WRAP_UP

DEPLOYMENT_TYPE:
    - name: SSH
      value: SSH
    - name: Amazon EC2 Container
      value: ECS
    - name: Kubernetes
      value: KUBERNETES
