CARD_VIEW_SORT_BY:
    - name: Most Recent
      value: mostRecent
    - name: Alphabetical Ascending
      value: alphabeticalAscending
    - name: Alphabetical Descending
      value: alphabeticalDescending
      
ARTIFACT_TYPE:
    - name: Docker Image
      value: DOCKER
    - name: Web Archive (WAR)
      value: WAR
    - name: Java Archive (JAR)
      value: JAR
    - name: TAR File
      value: TAR
    - name: ZIP File
      value: ZIP
    - name: RPM File
      value: RPM
    - name: Other
      value: OTHER
    - name: AWS Lambda
      value: AWS_LAMBDA
    - name: AWS Code Deploy
      value: AWS_CODEDEPLOY

ARTIFACT_SOURCE_TYPE:
    - name: Jenkins Server
      value: JENKINS
    - name: Bamboo Server
      value: BAMBOO
    - name: Docker Repository
      value: DOCKER
    - name: Nexus Repository
      value: NEXUS
    - name: Arifactory Server
      value: ARTIFACTORY

ARTIFACT_STREAM_TYPE:
    - name: JENKINS
      value: Jenkins
    - name: BAMBOO
      value: Bamboo
    - name: NEXUS
      value: Nexus
    - name: ARTIFACTORY
      value: Artifactory
    - name: AMAZON_S3
      value: Amazon S3
    - name: DOCKER
      value: Docker
    - name: ECR
      value: ECR
    - name: GCR
      value: GCR

DEPLOYMENT_STRATEGY:
    - name: Serial
      value: SERIAL
    - name: Parallel
      value: PARALLEL

OS_TYPE:
    - name: Linux - RHL
      value: RHL
    - name: Linux - DEB
      value: DEB

CONNECTION_TYPE:
    - name: SSH
      value: SSH
    - name: VPN
      value: VPN

ACCESS_TYPE:
    - name: SSH
      value: SSH
    - name: SSH_KEY
      value: SSH_KEY
    - name: SSH_USER_PASSWD
      value: SSH_USER_PASSWD
    - name: SSH_SU_APP_ACCOUNT
      value: SSH_SU_APP_ACCOUNT
    - name: SSH_SUDO_APP_ACCOUNT
      value: SSH_SUDO_APP_ACCOUNT

EXECUTION_TYPE:
    - name: SSH
      value: SSH

CONTAINER_FAMILY:
    - name: Tomcat
      value: TOMCAT
    - name: JBoss AS 7
      value: JBOSS

WORKFLOW_ORCHESTRATION_TYPE:
    - name: Basic
      value: BASIC
    - name: Multi-Service
      value: MULTI_SERVICE
    - name: Canary
      value: CANARY
    - name: Blue/Green
      value: BLUE_GREEN
    - name:  Rolling Upgrade
      value: ROLLING_UPGRADE
    - name: Custom Workflow
      value: CUSTOM

FAILURE_TYPE:
    - name: Connectivity Error
      value: CONNECTIVITY
    - name: Authentication Failure
      value: AUTHENTICATION
    - name: Verification Failure
      value: VERIFICATION_FAILURE
    - name: Application Error
      value: APPLICATION_ERROR

EXECUTION_SCOPE:
    - name: Workflow
      value: WORKFLOW
    - name: Workflow Phase
      value: WORKFLOW_PHASE

NOTIFICATION_CONDITION:
    - name: Success
      value: SUCCESS
    - name: Failure
      value: FAILED
    - name: Paused
      value: PAUSED

REPAIR_ACTION_CODE:
    - name: Manual Intervention
      value: MANUAL_INTERVENTION
    - name: Rollback Workflow Execution
      value: ROLLBACK_WORKFLOW
    - name: Rollback Phase Execution
      value: ROLLBACK_PHASE
    - name: Ignore
      value: IGNORE
    - name: Retry
      value: RETRY

ACTION_AFTER_RETRY:
    - name: Manual Intervention
      value: MANUAL_INTERVENTION
    - name: Rollback Workflow
      value: ROLLBACK_WORKFLOW
    - name: Rollback Phase
      value: ROLLBACK_PHASE
    - name: Ignore
      value: IGNORE
    - name: Retry
      value: RETRY

PHASE_STEP_TYPE:
    - name: Provision Nodes
      value: PROVISION_NODE
    - name: Disable/Unpublish Services
      value: DISABLE_SERVICE
    - name: Deploy Services
      value: INSTALL
    - name: Enable/Publish Services
      value: ENABLE_SERVICE
    - name: Verify Services
      value: VERIFY_SERVICE
    - name: Deprovision Nodes
      value: DEPROVISION_NODE
    - name: Wrap up
      value: WRAP_UP

DEPLOYMENT_TYPE:
    - name: Secure Shell (SSH)
      value: SSH
    - name: AWS CodeDeploy
      value: AWS_CODEDEPLOY
    - name: Amazon EC2 Container Services (ECS)
      value: ECS
    - name: Kubernetes
      value: KUBERNETES
    - name: AWS Lambda
      value: AWS_LAMBDA

ENVIRONMENT_TYPE:
    - name: Production
      value: PROD
    - name: Non Production
      value: NON_PROD

ROLE_TYPE:
    - name: Account Administrator
      value: ACCOUNT_ADMIN
    - name: Application Administrator
      value: APPLICATION_ADMIN
    - name: Production Support
      value: PROD_SUPPORT
    - name: Non-production Support
      value: NON_PROD_SUPPORT

OVERRIDE_TYPE:
    - name: Entire Environment
      value: ALL
    - name: Override Specific Instances
      value: INSTANCES
    - name: Override Specific Zones/Tags etc.
      value: CUSTOM

SERVICE_VARIABLE_TYPE:
    - name: Text
      value: TEXT
    - name: Encrypted Text
      value: ENCRYPTED_TEXT


LOG_DRIVER:
    - name: <none>
      value: ""
    - name: awslogs
      value: awslogs
    - name: splunk
      value: splunk
    - name: fluentd
      value: fluentd
    - name: gelf
      value: gelf
    - name: journald
      value: journald
    - name: json-file
      value: json-file
    - name: splunk
      value: splunk
    - name: syslog
      value: syslog

PLUGIN_CATEGORY:
    - name: Artifact Server
      value: Artifact
    - name: Cloud Provider
      value: CloudProvider
    - name: Verification Provider
      value: Verification
    - name: Collaboration Provider
      value: Collaboration
    - name: Load Balancer
      value: LoadBalancer
    - name: Connection Attributes
      value: ConnectionAttributes
    - name: AppDynamics
      value: APP_DYNAMICS

CLOUD_PROVIDERS:
    - name: Google Cloud Platform
      value: GCP
    - name: Amazon Web Services
      value: AWS
    - name: Physical Data Center
      value: PHYSICAL_DATA_CENTER
    - name: Direct Kubernetes
      value: DIRECT

FORM_FIELD_TO_ENTITY_TYPE:
    - name: envId
      value: ENVIRONMENT
    - name: serviceId
      value: SERVICE
    - name: infraMappingId
      value: INFRASTRUCTURE_MAPPING


TASK_TYPES:
    - name: Command
      value: COMMAND
    - name: HTTP Verification
      value: HTTP
    - name: Host Validation
      value: HOST_VALIDATION
    - name: Jenkins
      value: JENKINS
    - name: Bamboo
      value: BAMBOO
    - name: Nexus
      value: NEXUS
    - name: Artifactory
      value: ARTIFACTORY
    - name: Amazon S3
      value: S3
    - name: Docker Hub
      value: DOCKER
    - name: Amazon EC2 Container Registry
      value: ECR
    - name: Google Container Registry
      value: GCR
    - name: AppDynamics
      value: APPDYNAMICS
    - name: Splunk
      value: SPLUNK
    - name: Elk
      value: ELK
    - name: Logz
      value: LOGZ

EXECUTION_STATUS:
    - name: Aborted
      value: ABORTED
    - name: Aborting
      value: ABORTING
    - name: Error
      valeu: ERROR
    - name: Failed
      value: FAILED
    - name: Queued
      value: QUEUED
    - name: Pausing
      value: PAUSING
    - name: Paused
      value: PAUSED
    - name: Running
      value: RUNNING
    - name: Success
      value: SUCCESS
    - name: Waiting
      value: WAITING

ELK_CONNECTOR_TYPE:
    - name: Elastic Search Server
      value: ELASTIC_SEARCH_SERVER
    - name: Kibana Server
      value: KIBANA_SERVER

CONNECTOR_TYPES:
    - name: Jenkins
      value: JENKINS
    - name: Bamboo
      value: BAMBOO
    - name: Docker
      value: DOCKER REGISTRY
    - name: NEXUS
      value: Nexus
    - name: ARTIFACTORY
      value: Artifactory
    - name: APP_DYNAMICS
      value: AppDynamics
    - name: NEW_RELIC
      value: NewRelic
    - name: SPLUNK
      value: Splunk
    - name: ELK
      value: ELK
    - name: LOGZ
      value: LOGZ
    - name: SUMO
      value: SumoLogic
    - name: SMTP
      value: SMTP
    - name: SLACK
      value: SLACK

