plainTextPort: 9889
securePort: 9890
keyFilePath: key.pem
certFilePath: cert.pem
mongo:
  uri: mongodb://localhost:27017/harness

logging:
  level: INFO
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %blue(%X{executionId}) %cyan(%logger) - %msg %n"
    - type: rest-log
      threshold: TRACE
      logFormat: "%blue([${VERSION}]) %green([%thread]) %highlight(%-5level) %blue(%X{executionId}) %cyan(%logger) - %msg %n"
      key: 9a3e6eac4dcdbdc41a93ca99100537df
      programName: event-server
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      logFormat: "%blue([${VERSION}]) %green([%thread]) %highlight(%-5level) %blue(%X{executionId}) %cyan(%logger) - %msg %n"
      stackdriverLogEnabled: false
