connectors:
  - port: 9890
    secure: true
    keyFilePath: key.pem
    certFilePath: cert.pem
  - port: 9889
harness-mongo:
  uri: mongodb://localhost:27017/harness
events-mongo:
  uri: mongodb://localhost:27017/events
