name: Go Build
on:
  pull_request:
    branches:
      - master

jobs:
  gobuild:
    if: contains(github.event.pull_request.labels.*.name, 'go') || contains(github.event.pull_request.labels.*.name, 'gojava')
    name: Go Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Building commons code
        run: |
          echo "Building golang code using bazel..."
          bazel build //commons/...

      - name: Building product code
        run: |
          echo "Building golang product code using bazel..."
          bazel build //product/...

      - name: Testing commons
        run: |
          echo "Testing golang code using bazel..."
          bazel test --test_output=all //commons/...

      - name: Testing product
        run: |
          echo "Testing golang code using bazel..."
          bazel test --test_output=all //product/...

      - name: Coverage
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          echo $PATH
          echo $GOPATH
          echo "Adding gocovmerge package... "
          go get -u github.com/wadey/gocovmerge
          tools/go/generate_coverage.sh func
